apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: mysql-deployment
  labels:
    app: mysql
    app.kubernetes.io/name: mysql
spec:
  clusterIP: None
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-slave
  namespace: mysql-deployment
  labels:
    app: mysql
    app.kubernetes.io/name: mysql
    "readonly": "true"
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
