apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: mysql-deployment
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: bXktc2VjcmV0LXBhc3N3b3Jk # (base64 encoded)
  MYSQL_USER: bXl1c2Vy # (base64 encoded)
  MYSQL_PASSWORD: bXktcGFzc3dvcmQ= # (base64 encoded)