apiVersion: v1
kind: Service
metadata:
  name: kafka-external
  namespace: kafka
spec:
  type: LoadBalancer
  ports:
    - name: kafka
      port: 9094
      targetPort: 9094
  selector:
    app: kafka-app

